import {usePlanner} from '../hooks/PlannerContext';
import React from 'react';
import {useState} from 'react';
import {categories} from '../data/projects';

import {localDate} from '../utils/tasks';
import TaskList from '../components/TaskList';
import WeeklySchedule from '../components/WeeklySchedule';
import ExamList from '../components/ExamList';
export default function Home({data,now,onAdd,...actions}){const {projects,schedule}=usePlanner();const [filter,setFilter]=useState('all');const [showDone,setShowDone]=useState(false);const today=localDate(now);const classes=schedule.filter(c=>c.day===now.getDay());return <><section className="today"><div className="today-date"><h2>01 / TODAY</h2><p>{now.toLocaleDateString('en-US',{weekday:'short'}).toUpperCase()}<br/><em>{now.toLocaleDateString('en-US',{month:'short',day:'2-digit'}).toUpperCase()}</em></p><span>把今天，留給重要的事。</span></div><div className="today-classes"><h3>ON THE SCHEDULE <span>{String(classes.length).padStart(2,'0')}</span></h3>{classes.map(c=><a href={`#/project/${c.courseId}`} key={`${c.courseId}-${c.start}-${c.end}`}><time>{c.start} — {c.end}</time><strong>{projects.find(p=>p.id===c.courseId).name}</strong><span>↗</span></a>)}{!classes.length&&<p className="empty">今天沒有課程，照自己的步調來。</p>}</div><div className="today-tasks"><h3>TODAY'S TASKS <span>{data.tasks.filter(t=>t.deadline===today&&!t.completed).length}</span></h3>{data.tasks.filter(t=>t.deadline===today&&!t.completed).map(t=><label key={t.id}><input type="checkbox" checked={t.completed} onChange={()=>actions.onToggle(t.id)}/><span>{t.title}<small className={`tag ${t.category}`}>{categories[t.category]}</small></span></label>)}{!data.tasks.some(t=>t.deadline===today&&!t.completed)&&<p className="empty">今天到期的待辦都完成了。</p>}<button className="text-button" onClick={()=>onAdd()}>＋ QUICK TASK</button></div></section><section id="tasks"><div className="section-head"><h2>02 / MY TASKS <span className="count">{data.tasks.filter(t=>!t.completed).length}</span></h2><button className="primary" onClick={()=>onAdd()}>＋ QUICK TASK</button></div><div className="task-toolbar"><div className="filters">{[['all','ALL'],...Object.entries(categories)].map(([k,v])=><button key={k} className={filter===k?'active':''} onClick={()=>setFilter(k)}>{v}</button>)}</div><label className="show-done"><input type="checkbox" checked={showDone} onChange={e=>setShowDone(e.target.checked)}/>顯示已完成</label></div><TaskList tasks={data.tasks.filter(t=>(filter==='all'||t.category===filter)&&(showDone||!t.completed))} {...actions}/></section><section id="exams"><div className="section-head"><h2>03 / UPCOMING EXAMS</h2></div><ExamList exams={data.exams} now={now} upcoming/></section><WeeklySchedule now={now}/></>}

